env:
  - DOCKER_COMPOSE_VERSION=1.9.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - cd tests/airflow1.8-py2 && docker-compose up -d
  - pwd && sleep 30 # not sure how to dynamically wait
  - curl http://localhost:8080/admin/metrics
