sudo: false

services:
  - docker

# Docker-compose setup
# https://docs.travis-ci.com/user/docker/
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.9.0
    
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x tests/test_metrics_up.sh
  

script:
  # Test Airflow 1.8 with Python 2
  - cd tests/airflow1.8-py2 && docker-compose build --no-cache && docker-compose up -d
  - ${TRAVIS_BUILD_DIR}/tests/test_metrics_up.sh
  - docker-compose down

  # Test Airflow 1.9 with Python 3
  - mkdir ${TRAVIS_BUILD_DIR}/tests/airflow1.9-py3/airflow/logs
  - chmod -R 777 ${TRAVIS_BUILD_DIR}/tests/airflow1.9-py3/airflow/logs
  - cd ${TRAVIS_BUILD_DIR}/tests/airflow1.9-py3 && docker-compose build --no-cache && docker-compose up -d
  - ${TRAVIS_BUILD_DIR}/tests/test_metrics_up.sh
  - docker-compose down

  # Test Airflow 1.10 with Python 3
  - mkdir ${TRAVIS_BUILD_DIR}/tests/airflow1.10-py3/airflow/logs
  - chmod -R 777 ${TRAVIS_BUILD_DIR}/tests/airflow1.10-py3/airflow/logs
  - cd ${TRAVIS_BUILD_DIR}/tests/airflow1.10-py3 && docker-compose build --no-cache && docker-compose up -d
  - ${TRAVIS_BUILD_DIR}/tests/test_metrics_up.sh
  - docker-compose down

  # Test Airflow 1.10 with RBAC and Python 3
  - mkdir ${TRAVIS_BUILD_DIR}/tests/airflow1.10-rbac-py3/airflow/logs
  - chmod -R 777 ${TRAVIS_BUILD_DIR}/tests/airflow1.10-rbac-py3/airflow/logs
  - cd ${TRAVIS_BUILD_DIR}/tests/airflow1.10-rbac-py3 && docker-compose build --no-cache && docker-compose up -d
  - ${TRAVIS_BUILD_DIR}/tests/test_metrics_rbac_up.sh
  - docker-compose down
