version: '3'

services:
  sut:
    image: test_airflow_exporter
    build:
      context: ./tests
    environment:
      - AIRFLOW_BASE_URL=http://airflow:8080
      - AIRFLOW__WEBSERVER__RBAC
    depends_on:
      - airflow
