  
name: Test airflow-exporter

on:
  push:
    branches:
      - master
      - v1.3
  pull_request:
    branches:
      - '*'

jobs:

  test:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup DB
      run: |
        docker-compose up -d postgres
        docker-compose up initdb
    - name: Prepare DAG statuses
      run: |
        docker-compose run scheduler scheduler -n 1
        
        docker-compose run scheduler unpause dummy_dag
        docker-compose run scheduler unpause slow_dag
        docker-compose run scheduler trigger_dag dummy_dag
    - name: Wait for Airflow and query metrics
      run: |
        # Start the tests container (sut) and attach airflow stdout as well
        docker-compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from=sut sut scheduler webserver