name: Test airflow-exporter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:

  test:
 
    runs-on: ubuntu-latest
    services:
      postgres:
        image: "postgres:9.6"
        env:
          POSTGRES_USER: airflow
          POSTGRES_PASSWORD: airflow
          POSTGRES_DB: airflow
        ports:
        - "5432:5432"

    env:
      AIRFLOW_HOME: tests/

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Airflow
      run: pip install "apache-airflow >= 2.2.0" psycopg2-binary wtforms==2.3.3

    - name: Install airflow-exporter
      run: pip install .

    - name: Prepare DAG statuses
      run: |
        airflow db init

        airflow scheduler -n 1

        airflow dags unpause dummy_dag
        airflow dags unpause slow_dag

        # airflow scheduler -n 1
        # airflow dags trigger dummy_dag

    - name: Wait for Airflow and query metrics
      run: |
        airflow webserver & python tests/test_metrics_up.py
