name: Test airflow-exporter

on: [push]

jobs:

  test:
 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - airflow_version: 1.10.4
            airflow_rbac: false
          
          - airflow_version: 1.10.4
            airflow_rbac: true
 
    steps:
    - uses: actions/checkout@v1
    - name: Run test
      env:
        AIRFLOW_VERSION: ${{ matrix.airflow_version }}
        AIRFLOW__WEBSERVER__RBAC: ${{ matrix.airflow_rbac }}

      run: |
        docker-compose up -d postgresql
        docker-compose run airflow /entrypoint.sh airflow initdb
        docker-compose run airflow /entrypoint.sh airflow unpause dummy_dag
        docker-compose run airflow /entrypoint.sh airflow trigger_dag dummy_dag

        # Start the tests container (sut) and attach airflow stdout as well
        docker-compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from=sut sut airflow
